'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'
import { SupportedLanguage, WHATSAPP_DISPLAY_NUMBER } from '@/config/constants'
import { detectUserLanguage } from '@/utils/detectUserLanguage'

type Language = SupportedLanguage

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.contact': 'Contact Us',
    'hero.logo.travels': 'TRAVELS',
    'hero.headline': 'Buy your trip with protected payment',
    'hero.subheadline': 'Security and trust, personalized service and the freedom to pay for your trip with cryptocurrencies, card, boleto or Pix. Travel with those who understand the future.',
    'hero.cta': 'Get a personalized quote',
    'hero.badge.support': 'Personalized Support',
    'hero.badge.payment': 'Crypto • Card • Pix • Boleto',
    'hero.badge.worldwide': 'Worldwide Service',
    'services.title': 'Our Services',
    'services.flights': 'Flights',
    'services.hotels': 'Hotels',
    'services.insurance': 'Travel Insurance',
    'services.tours': 'Tours',
    'services.car': 'Car Rental',
    'services.cruises': 'Cruises',
    'search.stops': 'stop',
    'search.stopsPlural': 'stops',
    'search.direct': 'Direct',
    'search.connectionAt': 'Connection at',
    'search.flightDuration': 'Flight duration',
    'search.operatedBy': 'Operated by',
    'search.availableOptions': 'available options',
    'search.finalRoundTrip': 'Final round-trip',
    'search.finalTotal': 'Final',
    'search.finalPerson': 'person',
    'search.finalPersons': 'people',
    'checkout.pricePerAdult': 'Price per adult',
    'checkout.pricePerChild': 'Price per child',
    'checkout.pricePerBaby': 'Price per infant',
    'checkout.leg': 'LEG',
    'checkout.departure': 'DEPARTURE',
    'checkout.return': 'RETURN',
    'checkout.duration': 'Duration',
    'checkout.connectionAt': 'Connection at',
    'checkout.operatedBy': 'Operated by',
    'checkout.simulatedPrice': 'SIMULATED PRICE',
    'why.title': 'Why Bit Travels?',
    'why.security.title': 'Security First',
    'why.security.desc': 'We are a consolidated agency, with transparent processes and total support from start to finish of your journey.',
    'why.crypto.title': 'Crypto Pioneering',
    'why.crypto.desc': 'We were born in the crypto world. We accept your digital assets (BTC, ETH, USDT, others) directly, plus Pix, boleto and card.',
    'why.support.title': 'Personalized Service and Support',
    'why.support.desc': 'We are not robots. You will have a dedicated consultant to take care of itineraries, visas, check-in and any unforeseen events.',
    'comparison.title': 'Compare & Choose the Best',
    'comparison.feature': 'Feature',
    'comparison.airline': 'Others',
    'comparison.ota': 'Others',
    'comparison.bitmiles': 'Bit Travels',
    'comparison.price': 'Price',
    'comparison.price.high': 'High',
    'comparison.price.average': 'Average',
    'comparison.price.lowest': 'Fair',
    'comparison.payment': 'Payment',
    'comparison.payment.card': 'Card/Pix',
    'comparison.payment.cardPix': 'Card/Pix',
    'comparison.payment.all': 'Cryptocurrencies, card, pix and boleto',
    'comparison.support': 'Support',
    'comparison.support.call': 'Generic Call Centers',
    'comparison.support.bots': 'Bots/Automated',
    'comparison.support.concierge': 'Personalized Human Support (PT/EN/ES)',
    'comparison.extras': 'Extras',
    'comparison.extras.none': 'None',
    'comparison.extras.included': 'Support from start to finish, monitoring and Legal Support',
    'testimonials.title': 'What Our Customers Say',
    'footer.copyright': 'Bit Travels LTDA',
    'footer.rights': 'All rights reserved.',
    'passengers.adults': 'Adults',
    'passengers.adult': 'Adult',
    'passengers.children': 'Children',
    'passengers.child': 'Child',
    'passengers.childrenTitle': 'Minors',
    'passengers.adultsDescription': '18+ years',
    'passengers.childrenDescription': 'Up to 17 years',
    'passengers.age': 'Age',
    'passengers.upTo1': 'Up to 1 year',
    'passengers.year': 'year',
    'passengers.years': 'years',
    'confirm': 'Confirm',
    'footer.description': 'Buy your trip with protected payment. Travel with those who understand the future.',
    'oneWay': 'One-way',
    'roundTrip': 'Round-trip',
    'multiCity': 'Multi-city',
    'multiCityDescription': 'Add up to 5 segments for your multi-city trip',
    'searching': 'Searching...',
    'flightsFound': 'flights found',
    'remove': 'Remove',
    'addSegment': 'Add Segment',
    'search.origin': 'Origin',
    'search.destination': 'Destination',
    'search.departure': 'Departure Date',
    'search.return': 'Return Date',
    'search.passengers': 'Passengers',
    'search.passengers.adults': 'Adults',
    'search.passengers.children': 'Children',
    'search.button': 'Search Flights',
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'Why buy with Bit Travels?',
    'faq.a1': 'Because we are an agency that understands the future. In addition to accepting cryptocurrencies, we offer human and high-performance service. We take care of all the bureaucracy, perform your check-in, monitor your flight in real time and ensure that your only concern is your trip.',
    'faq.q2': 'How does Bit Travels work?',
    'faq.a2': 'Bit Travels is a high-standard travel agency that takes care of everything for you. In addition to offering various forms of payment (including crypto), we perform your check-in, guide you on all travel requirements and monitor your flight. Your only job is to travel.',
    'faq.q3': 'How do I pay with cryptocurrencies?',
    'faq.a3': 'We are one of the first agencies to accept cryptocurrencies in the world. After choosing your flight, at the payment stage you can select the cryptocurrency of your choice (Bitcoin, Ethereum, USDT and others). Our team guides you throughout the process.',
    'faq.q4': 'What forms of payment are accepted?',
    'faq.a4': 'We accept cryptocurrencies (BTC, ETH, USDT and others), credit card, Pix and bank slip. Our platform offers total flexibility for you to pay the way you want.',
    'faq.q5': 'Can I talk to a consultant before buying?',
    'faq.a5': 'Yes! Our service is humanized and consultative. We are available via WhatsApp to plan your itinerary, answer questions about visas and vaccines, and ensure your experience is perfect from the moment of booking.',
    'faq.q6': 'Is it safe to buy through Bit Travels?',
    'faq.a6': 'Totally safe. We are a travel agency with human and personalized service, we offer monitoring throughout your journey. We notify you of any changes to your flight and resolve any unexpected events for you.',
    'faq.q7': 'Can I buy tickets for international destinations?',
    'faq.a7': 'Yes! We serve the whole world. In addition to issuing the ticket, we guide you on all international requirements, such as travel insurance, visas and health protocols, so you can travel without concerns.',
    'faq.q8': 'What happens after I book my flight?',
    'faq.a8': 'We take command. We perform your check-in automatically, send all documents ready, notify you of any gate or time changes and provide full monitoring of your trip. You only need to worry about traveling.',
    'faq.q9': 'Does Bit Travels offer travel insurance?',
    'faq.a9': 'Yes! We offer travel insurance as an additional service. We strongly recommend taking out insurance, especially for international trips, ensuring protection in cases of cancellations, medical emergencies and baggage.',
    'faq.q10': 'How to cancel or change a reservation?',
    'faq.a10': 'Contact our team via WhatsApp or email. Cancellation and change conditions vary according to the airline policy and the fare purchased. Our consultants will guide you in each case.',
    'fare.economy': 'Economy Class',
    'fare.checkedBaggage': 'Checked baggage',
    'fare.bagIncluded': 'bag included',
    'fare.bagsIncluded': 'bags included',
    'fare.totalPerPerson': 'Total price per person',
    'checkout.title': 'Complete Booking',
    'checkout.subtitle': 'Complete the details to confirm your trip',
    'checkout.back': 'Back to search',
    'checkout.whoTravels': 'Who is traveling?',
    'checkout.contactData': 'Contact Data',
    'checkout.contactSub': 'where we will send the payment link and booking info',
    'checkout.email': 'E-mail',
    'checkout.whatsapp': 'WhatsApp *',
    'checkout.whatsappPlaceholder': '+55 (AA) 99999-9999',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.paymentMethodSub': 'How would you like to pay',
    'checkout.payment.pix': 'Pix',
    'checkout.payment.boleto': 'Bank Slip',
    'checkout.payment.card': 'Credit Card',
    'checkout.payment.crypto': 'Cryptocurrencies',
    'checkout.submit': 'Continue',
    'checkout.processing': 'Processing...',
    'checkout.paymentDetails': 'Payment Details',
    'checkout.flightFor': 'Flight for',
    'checkout.taxes': 'taxes and fees',
    'checkout.total': 'Total',
    'checkout.successTitle': 'Booking in Progress!',
    'checkout.successMessage': `Your booking is in progress. A Bit Travels specialist will contact you on WhatsApp ${WHATSAPP_DISPLAY_NUMBER} to finish booking and payment.`,
    'checkout.bookingId': 'Booking ID',
    'checkout.talkToSpecialist': 'Talk to an Agent',
    'passenger.adult': 'Adult',
    'passenger.child': 'Child',
    'passenger.baby': 'Infant',
    'passenger.fillData': 'Fill data according to the document',
    'passenger.nameLabel': 'First Name *',
    'passenger.nameSub': 'As it appears on ID',
    'passenger.lastNameLabel': 'Last Name *',
    'passenger.lastNameSub': 'Ex: Smith',
    'search.select': 'Select',
    'search.backpackOption': 'Includes a personal item',
    'search.backpackSub': 'Must fit under the seat in front of you.',
    'search.carryonOption': 'Includes carry-on bag',
    'search.carryonSub': 'Must fit in the overhead bin.',
    'search.noCheckedOption': 'No checked bag included',
    'search.noCheckedSub': 'You can add bags later for an additional fee.',
    'fare.fallbackLabel': 'Available Fare',
    'fare.fallbackName': 'Fare',
    'fare.selected': 'Selected',
    'search.roundTripFare': 'Round-trip Fare',
    'search.errorTitle': 'Error searching flights:',
    'search.priceCombination': 'price combination',
    'search.priceCombinations': 'price combinations',
    'passenger.babies': 'Infants',
    'nav.flights': 'Flights',
    'ticket.print': 'Print Ticket',
    'ticket.generating': 'Generating your ticket...',
    'ticket.status': 'Confirmed',
    'passenger.country': 'Country of residence',
    'passenger.selectCountry': 'Select country',
    'passenger.documentType': 'Document type',
    'passenger.selectDocument': 'Select type',
    'passenger.passportRequired': 'Required for passengers residing outside Brazil',
    'passenger.document': 'Document',
    'passenger.birthDate': 'Date of birth',
    'passenger.day': 'Day',
    'passenger.month': 'Month',
    'passenger.year': 'Year',
    'passenger.gender': 'Gender',
    'passenger.female': 'Female',
    'passenger.male': 'Male',
    'passenger.month.jan': 'January',
    'passenger.month.feb': 'February',
    'passenger.month.mar': 'March',
    'passenger.month.apr': 'April',
    'passenger.month.may': 'May',
    'passenger.month.jun': 'June',
    'passenger.month.jul': 'July',
    'passenger.month.aug': 'August',
    'passenger.month.sep': 'September',
    'passenger.month.oct': 'October',
    'passenger.month.nov': 'November',
    'passenger.month.dec': 'December',
    'country.brasil': 'Brazil',
    'country.argentina': 'Argentina',
    'country.chile': 'Chile',
    'country.colombia': 'Colombia',
    'country.estados unidos': 'United States',
    'country.portugal': 'Portugal',
    'country.espanha': 'Spain',
    'country.franca': 'France',
    'country.italia': 'Italy',
    'country.alemanha': 'Germany',
    'country.outro': 'Other',
  },
  pt: {
    'nav.contact': 'Fale Conosco',
    'hero.logo.travels': 'VIAGENS',
    'hero.headline': 'Compre sua viagem com pagamento protegido',
    'hero.subheadline': 'Segurança e confiança, atendimento personalizado e a liberdade de pagar sua viagem com criptomoedas, cartão, boleto ou Pix. Viaje com quem entende do futuro.',
    'hero.cta': 'Receba um orçamento personalizado',
    'hero.badge.support': 'Suporte Personalizado',
    'hero.badge.payment': 'Crypto • Cartão • Pix • Boleto',
    'hero.badge.worldwide': 'Serviço Mundial',
    'services.title': 'Nossos Serviços',
    'services.flights': 'Voos',
    'services.hotels': 'Hotéis',
    'services.insurance': 'Seguro Viagem',
    'services.tours': 'Passeios',
    'services.car': 'Aluguel de Carro',
    'services.cruises': 'Cruzeiros',
    'search.stops': 'escala',
    'search.stopsPlural': 'escalas',
    'search.direct': 'Direto',
    'search.connectionAt': 'Conexão em',
    'search.flightDuration': 'Duração do voo',
    'search.operatedBy': 'Operado por',
    'search.availableOptions': 'opções disponíveis',
    'search.finalRoundTrip': 'Final ida e volta',
    'search.finalTotal': 'Final',
    'search.finalPerson': 'pessoa',
    'search.finalPersons': 'pessoas',
    'checkout.pricePerAdult': 'Preço por adulto',
    'checkout.pricePerChild': 'Preço por criança',
    'checkout.pricePerBaby': 'Preço por bebê',
    'checkout.leg': 'TRECHO',
    'checkout.departure': 'IDA',
    'checkout.return': 'VOLTA',
    'checkout.duration': 'Duração',
    'checkout.connectionAt': 'Conexão em',
    'checkout.operatedBy': 'Operado por',
    'checkout.simulatedPrice': 'PREÇO SIMULADO',
    'why.title': 'Por que Bit Travels?',
    'why.security.title': 'Segurança em Primeiro Lugar',
    'why.security.desc': 'Somos uma agência consolidada, com processos transparentes e suporte total do início ao fim da sua jornada.',
    'why.crypto.title': 'Pioneirismo em Cripto',
    'why.crypto.desc': 'Nascemos no mundo cripto. Aceitamos seus ativos digitais (BTC, ETH, USDT, outros) diretamente, além de Pix, boleto e cartão.',
    'why.support.title': 'Atendimento e Suporte Personalizado',
    'why.support.desc': 'Não somos robôs. Você terá um consultor dedicado para cuidar de roteiros, vistos, check-in e qualquer imprevisto.',
    'comparison.title': 'Compare e Escolha o Melhor',
    'comparison.feature': 'Recurso',
    'comparison.airline': 'Companhia Aérea',
    'comparison.ota': 'Sites Padrão',
    'comparison.bitmiles': 'Bit Travels',
    'comparison.price': 'Preço',
    'comparison.price.high': 'Alto',
    'comparison.price.average': 'Médio',
    'comparison.price.lowest': 'Justo',
    'comparison.payment': 'Pagamento',
    'comparison.payment.card': 'Cartão/Pix',
    'comparison.payment.cardPix': 'Cartão/Pix',
    'comparison.payment.all': 'Criptomoedas, cartão, pix e boleto',
    'comparison.support': 'Suporte',
    'comparison.support.call': 'Centrais de Atendimento genéricas',
    'comparison.support.bots': 'Bots/Automatizado',
    'comparison.support.concierge': 'Suporte Humano Personalizado (PT/EN/ES)',
    'comparison.extras': 'Extras',
    'comparison.extras.none': 'Nenhum',
    'comparison.extras.included': 'Acompanhamento do inicio ao fim, monitoramento e Suporte juridico',
    'testimonials.title': 'O que Nossos Clientes Dizem',
    'footer.copyright': 'Bit Travels LTDA',
    'footer.rights': 'Todos os direitos reservados.',
    'passengers.adults': 'Adultos',
    'passengers.adult': 'Adulto',
    'passengers.children': 'Crianças',
    'passengers.child': 'Criança',
    'passengers.childrenTitle': 'Menores',
    'passengers.adultsDescription': 'A partir de 18 anos',
    'passengers.childrenDescription': 'Até 17 anos',
    'passengers.age': 'Idade',
    'passengers.upTo1': 'Até 1 ano',
    'passengers.year': 'ano',
    'passengers.years': 'anos',
    'confirm': 'Confirmar',
    'footer.description': 'Compre sua viagem com pagamento protegido. Viaje com quem entende do futuro.',
    'oneWay': 'Somente Ida',
    'roundTrip': 'Ida e Volta',
    'multiCity': 'Multidestino',
    'searching': 'Buscando...',
    'flightsFound': 'voos encontrados',
    'remove': 'Remover',
    'addSegment': 'Adicionar Trecho',
    'search.origin': 'Origem',
    'search.destination': 'Destino',
    'search.departure': 'Data de Ida',
    'search.return': 'Data de Volta',
    'search.passengers': 'Passageiros',
    'search.passengers.adults': 'Maiores',
    'search.passengers.children': 'Menores',
    'search.button': 'Buscar Voos',
    'faq.title': 'Perguntas Frequentes',
    'faq.q1': 'Por que comprar com a Bit Travels?',
    'faq.a1': 'Porque somos uma agência que entende o futuro. Além de aceitarmos criptomoedas, oferecemos um atendimento humano e de alta performance. Nós cuidamos de toda a burocracia, realizamos seu check-in, monitoramos seu voo em tempo real e garantimos que sua única preocupação seja a sua viagem.',
    'faq.q2': 'Como funciona a Bit Travels?',
    'faq.a2': 'A Bit Travels é uma agência de viagens de alto padrão que cuida de tudo para você. Além de oferecer diversas formas de pagamento (incluindo cripto), nós realizamos o seu check-in, orientamos sobre todos os requisitos da viagem e monitoramos seu voo. O seu único trabalho é viajar.',
    'faq.q3': 'Como faço para pagar com criptomoedas?',
    'faq.a3': 'Somos uma das primeiras agências a aceitar criptomoedas no mundo. Após escolher seu voo, na etapa de pagamento você poderá selecionar a criptomoeda de sua preferência (Bitcoin, Ethereum, USDT e outras). Nossa equipe te orienta em todo o processo.',
    'faq.q4': 'Quais formas de pagamento são aceitas?',
    'faq.a4': 'Aceitamos criptomoedas (BTC, ETH, USDT e outras), cartão de crédito, Pix e boleto bancário. Nossa plataforma oferece flexibilidade total para que você pague do jeito que quiser.',
    'faq.q5': 'Posso falar com um consultor antes de comprar?',
    'faq.a5': 'Sim! Nosso atendimento é humanizado e consultivo. Estamos disponíveis via WhatsApp para planejar seu roteiro, tirar dúvidas sobre vistos e vacinas, e garantir que sua experiência seja perfeita desde a reserva.',
    'faq.q6': 'É seguro comprar pela Bit Travels?',
    'faq.a6': 'Totalmente seguro. Somos uma agência de viagens com atendimento humano e personalizado, oferecemos acompanhamento durante toda a sua jornada. Avisamos sobre qualquer alteração no seu voo e resolvemos qualquer imprevisto por você.',
    'faq.q7': 'Posso comprar passagens para destinos internacionais?',
    'faq.a7': 'Sim! Atendemos o mundo inteiro. Além da emissão da passagem, orientamos você sobre todos os requisitos internacionais, como seguro viagem, vistos e protocolos sanitários, para que você viaje sem preocupações.',
    'faq.q8': 'O que acontece depois que eu reservar meu voo?',
    'faq.a8': 'Nós assumimos o comando. Realizamos seu check-in automaticamente, enviamos todos os documentos prontos, avisamos sobre qualquer alteração de portão ou horário e fazemos o acompanhamento total da sua viagem. Você só precisa se preocupar em viajar.',
    'faq.q9': 'A Bit Travels oferece seguro viagem?',
    'faq.a9': 'Sim! Oferecemos seguro viagem como serviço adicional. Recomendamos fortemente contratar um seguro, especialmente para viagens internacionais, garantindo proteção em casos de cancelamentos, emergências médicas e bagagem.',
    'faq.q10': 'Como cancelar ou alterar uma reserva?',
    'faq.a10': 'Entre em contato com nossa equipe via WhatsApp ou e-mail. As condições de cancelamento e alteração variam conforme a política da companhia aérea e a tarifa adquirida. Nossos consultores irão te orientar em cada caso.',
    'fare.economy': 'Classe Econômica',
    'fare.checkedBaggage': 'Bagagem despachada',
    'fare.bagIncluded': 'mala inclusa',
    'fare.bagsIncluded': 'malas inclusas',
    'fare.totalPerPerson': 'Preço total por pessoa',
    'checkout.title': 'Finalizar Reserva',
    'checkout.subtitle': 'Complete os dados para confirmar sua viagem',
    'checkout.back': 'Voltar para a busca',
    'checkout.whoTravels': 'Quem viaja?',
    'checkout.contactData': 'Dados de Contato',
    'checkout.contactSub': 'onde enviaremos o link de pagamento e informações da reserva',
    'checkout.email': 'E-mail',
    'checkout.whatsapp': 'WhatsApp *',
    'checkout.whatsappPlaceholder': '55 (DD) 99999-9999',
    'checkout.paymentMethod': 'Forma de Pagamento',
    'checkout.paymentMethodSub': 'Como prefere pagar sua viagem',
    'checkout.payment.pix': 'Pix',
    'checkout.payment.boleto': 'Boleto Bancário',
    'checkout.payment.card': 'Cartão de Crédito',
    'checkout.payment.crypto': 'Criptomoedas',
    'checkout.submit': 'Continuar',
    'checkout.processing': 'Processando...',
    'checkout.paymentDetails': 'Detalhes do Pagamento',
    'checkout.flightFor': 'Voo para',
    'checkout.taxes': 'impostos e taxas',
    'checkout.total': 'Total',
    'checkout.successTitle': 'Reserva em Andamento!',
    'checkout.successMessage': `Sua reserva está em andamento. Um especialista da Bit Travels entrará em contato pelo WhatsApp ${WHATSAPP_DISPLAY_NUMBER} para finalizar a reserva e o pagamento.`,
    'checkout.bookingId': 'ID da Reserva',
    'checkout.talkToSpecialist': 'Fale com um Atendente',
    'passenger.adult': 'Adulto',
    'passenger.child': 'Criança',
    'passenger.baby': 'Bebê',
    'passenger.fillData': 'Preencha os dados conforme o documento',
    'passenger.nameLabel': 'Nome *',
    'passenger.nameSub': 'Como está no documento',
    'passenger.lastNameLabel': 'Sobrenome *',
    'passenger.lastNameSub': 'Ex: Silva',
    'search.select': 'Selecionar',
    'search.backpackOption': 'Inclui uma mochila ou bolsa',
    'search.backpackSub': 'Deve caber embaixo do assento dianteiro.',
    'search.carryonOption': 'Inclui bagagem de mão',
    'search.carryonSub': 'Deve caber no compartimento superior do avião.',
    'search.noCheckedOption': 'Não inclui bagagem para despachar',
    'search.noCheckedSub': 'Você poderá adicionar malas por um valor adicional.',
    'fare.fallbackLabel': 'Tarifa Disponível',
    'fare.fallbackName': 'Tarifa',
    'fare.selected': 'Selecionado',
    'search.roundTripFare': 'Tarifa para Ida e Volta',
    'search.errorTitle': 'Erro ao buscar voos:',
    'search.priceCombination': 'combinação de preço',
    'search.priceCombinations': 'combinações de preço',
    'passenger.babies': 'Bebês',
    'nav.flights': 'Voo',
    'ticket.print': 'Imprimir Bilhete',
    'ticket.generating': 'Gerando seu bilhete...',
    'ticket.status': 'Confirmado',
    'passenger.country': 'País de residência',
    'passenger.selectCountry': 'Selecione o país',
    'passenger.documentType': 'Tipo de documento',
    'passenger.selectDocument': 'Selecione o tipo',
    'passenger.passportRequired': 'Obrigatório para passageiros residentes fora do Brasil',
    'passenger.document': 'Documento',
    'passenger.birthDate': 'Data de nascimento',
    'passenger.day': 'Dia',
    'passenger.month': 'Mês',
    'passenger.year': 'Ano',
    'passenger.gender': 'Sexo',
    'passenger.female': 'Feminino',
    'passenger.male': 'Masculino',
    'passenger.month.jan': 'Janeiro',
    'passenger.month.feb': 'Fevereiro',
    'passenger.month.mar': 'Março',
    'passenger.month.apr': 'Abril',
    'passenger.month.may': 'Maio',
    'passenger.month.jun': 'Junho',
    'passenger.month.jul': 'Julho',
    'passenger.month.aug': 'Agosto',
    'passenger.month.sep': 'Setembro',
    'passenger.month.oct': 'Outubro',
    'passenger.month.nov': 'Novembro',
    'passenger.month.dec': 'Dezembro',
    'country.brasil': 'Brasil',
    'country.argentina': 'Argentina',
    'country.chile': 'Chile',
    'country.colombia': 'Colômbia',
    'country.estados unidos': 'Estados Unidos',
    'country.portugal': 'Portugal',
    'country.espanha': 'Espanha',
    'country.franca': 'França',
    'country.italia': 'Itália',
    'country.alemanha': 'Alemanha',
    'country.outro': 'Outro',
  },
  es: {
    'nav.contact': 'Contáctanos',
    'hero.logo.travels': 'VIAJES',
    'hero.headline': 'Compra tu viaje con pago protegido',
    'hero.subheadline': 'Seguridad y confianza, atención personalizada y la libertad de pagar tu viaje con criptomonedas, tarjeta, boleto o Pix. Viaja con quienes entienden el futuro.',
    'hero.cta': 'Reciba un presupuesto personalizado',
    'hero.badge.support': 'Soporte Personalizado',
    'hero.badge.payment': 'Crypto • Tarjeta • Pix • Boleto',
    'hero.badge.worldwide': 'Servicio Mundial',
    'services.title': 'Nuestros Servicios',
    'services.flights': 'Vuelos',
    'services.hotels': 'Hoteles',
    'services.insurance': 'Seguro de Viaje',
    'services.tours': 'Tours',
    'services.car': 'Alquiler de Auto',
    'services.cruises': 'Cruceros',
    'search.stops': 'escala',
    'search.stopsPlural': 'escalas',
    'search.direct': 'Directo',
    'search.connectionAt': 'Conexión en',
    'search.flightDuration': 'Duración del vuelo',
    'search.operatedBy': 'Operado por',
    'search.availableOptions': 'opciones disponibles',
    'search.finalRoundTrip': 'Final ida y vuelta',
    'search.finalTotal': 'Final',
    'search.finalPerson': 'persona',
    'search.finalPersons': 'personas',
    'checkout.pricePerAdult': 'Precio por adulto',
    'checkout.pricePerChild': 'Precio por niño',
    'checkout.pricePerBaby': 'Precio por bebé',
    'checkout.leg': 'TRAMO',
    'checkout.departure': 'IDA',
    'checkout.return': 'VUELTA',
    'checkout.duration': 'Duración',
    'checkout.connectionAt': 'Conexión en',
    'checkout.operatedBy': 'Operado por',
    'checkout.simulatedPrice': 'PRECIO SIMULADO',
    'why.title': '¿Por qué Bit Travels?',
    'why.security.title': 'Seguridad Primero',
    'why.security.desc': 'Somos una agencia consolidada, con procesos transparentes y soporte total de principio a fin de tu viaje.',
    'why.crypto.title': 'Pionerismo en Cripto',
    'why.crypto.desc': 'Nacimos en el mundo cripto. Aceptamos tus activos digitales (BTC, ETH, USDT, otros) directamente, además de Pix, boleto y tarjeta.',
    'why.support.title': 'Atención y Soporte Personalizado',
    'why.support.desc': 'No somos robots. Tendrás un consultor dedicado para cuidar de itinerarios, visados, check-in y cualquier imprevisto.',
    'comparison.title': 'Compara y Elige el Mejor',
    'comparison.feature': 'Característica',
    'comparison.airline': 'Otros',
    'comparison.ota': 'Otros',
    'comparison.bitmiles': 'Bit Travels',
    'comparison.price': 'Precio',
    'comparison.price.high': 'Alto',
    'comparison.price.average': 'Medio',
    'comparison.price.lowest': 'Justo',
    'comparison.payment': 'Pago',
    'comparison.payment.card': 'Tarjeta/Pix',
    'comparison.payment.cardPix': 'Tarjeta/Pix',
    'comparison.payment.all': 'Criptomonedas, tarjeta, pix y boleto',
    'comparison.support': 'Soporte',
    'comparison.support.call': 'Centros de Atención Genéricos',
    'comparison.support.bots': 'Bots/Automatizado',
    'comparison.support.concierge': 'Soporte Humano Personalizado (PT/EN/ES)',
    'comparison.extras': 'Extras',
    'comparison.extras.none': 'Ninguno',
    'comparison.extras.included': 'Acompañamiento de principio a fin, monitoreo y Soporte juridico',
    'testimonials.title': 'Lo que Dicen Nuestros Clientes',
    'footer.copyright': 'Bit Travels LTDA',
    'footer.rights': 'Todos los derechos reservados.',
    'passengers.adults': 'Adultos',
    'passengers.adult': 'Adulto',
    'passengers.children': 'Niños',
    'passengers.child': 'Niño',
    'passengers.childrenTitle': 'Menores',
    'passengers.adultsDescription': 'A partir de 18 años',
    'passengers.childrenDescription': 'Hasta 17 años',
    'passengers.age': 'Edad',
    'passengers.upTo1': 'Hasta 1 año',
    'passengers.year': 'año',
    'passengers.years': 'años',
    'confirm': 'Confirmar',
    'footer.description': 'Compra tu viaje con pago protegido. Viaja con quienes entienden el futuro.',
    'oneWay': 'Solo ida',
    'roundTrip': 'Ida y vuelta',
    'multiCity': 'Multidestino',
    'searching': 'Buscando...',
    'flightsFound': 'vuelos encontrados',
    'remove': 'Eliminar',
    'addSegment': 'Añadir Tramo',
    'search.origin': 'Origen',
    'search.destination': 'Destino',
    'search.departure': 'Fecha de Ida',
    'search.return': 'Fecha de Vuelta',
    'search.passengers': 'Pasajeros',
    'search.passengers.adults': 'Adultos',
    'search.passengers.children': 'Niños',
    'search.button': 'Buscar Vuelos',
    'faq.title': 'Preguntas Frecuentes',
    'faq.q1': '¿Por qué comprar con Bit Travels?',
    'faq.a1': 'Porque somos una agencia que entiende el futuro. Además de aceptar criptomonedas, ofrecemos una atención humana y de alto rendimiento. Nos encargamos de toda la burocracia, realizamos su check-in, monitoreamos su vuelo en tiempo real y garantizamos que su única preocupación sea su viaje.',
    'faq.q2': '¿Cómo funciona Bit Travels?',
    'faq.a2': 'Bit Travels es una agencia de viajes de alto nivel que se encarga de todo por usted. Además de ofrecer diversas formas de pago (incluyendo cripto), realizamos su check-in, le orientamos sobre todos los requisitos del viaje y monitoreamos su vuelo. Su único trabajo es viajar.',
    'faq.q3': '¿Cómo pago con criptomonedas?',
    'faq.a3': 'Somos una de las primeras agencias en aceptar criptomonedas en el mundo. Después de elegir su vuelo, en la etapa de pago podrá seleccionar la criptomoneda de su preferencia (Bitcoin, Ethereum, USDT y otras). Nuestro equipo le orienta en todo el proceso.',
    'faq.q4': '¿Qué formas de pago se aceptan?',
    'faq.a4': 'Aceptamos criptomonedas (BTC, ETH, USDT y otras), tarjeta de crédito, Pix y boleta bancaria. Nuestra plataforma ofrece flexibilidad total para que pague como quiera.',
    'faq.q5': '¿Puedo hablar con un consultor antes de comprar?',
    'faq.a5': '¡Sí! Nuestra atención es humanizada y consultiva. Estamos disponibles vía WhatsApp para planificar su itinerario, aclarar dudas sobre visas y vacunas, y garantizar que su experiencia sea perfecta desde la reserva.',
    'faq.q6': '¿Es seguro comprar por Bit Travels?',
    'faq.a6': 'Totalmente seguro. Somos una agencia de viajes con atención humana y personalizada, ofrecemos acompañamiento durante toda su jornada. Le avisamos sobre cualquier cambio en su vuelo y resolvemos cualquier imprevisto por usted.',
    'faq.q7': '¿Puedo comprar boletos para destinos internacionales?',
    'faq.a7': '¡Sí! Atendemos a todo el mundo. Además de la emisión del boleto, le orientamos sobre todos los requisitos internacionales, como seguro de viaje, visas y protocolos sanitarios, para que viaje sin preocupaciones.',
    'faq.q8': '¿Qué sucede después de reservar mi vuelo?',
    'faq.a8': 'Nosotros asumimos el mando. Realizamos su check-in automáticamente, enviamos todos los documentos listos, avisamos sobre cualquier cambio de puerta o horario y hacemos el seguimiento total de su viaje. Solo necesita preocuparse por viajar.',
    'faq.q9': '¿Ofrece Bit Travels seguro de viaje?',
    'faq.a9': '¡Sí! Ofrecemos seguro de viaje como servicio adicional. Recomendamos encarecidamente contratar un seguro, especialmente para viajes internacionales, garantizando protección en casos de cancelaciones, emergencias médicas y equipaje.',
    'faq.q10': '¿Cómo cancelar o cambiar una reserva?',
    'faq.a10': 'Póngase en contacto con nuestro equipo a través de WhatsApp o correo electrónico. Las condiciones de cancelación y cambio varían según la política de la aerolínea y la tarifa adquirida. Nuestros consultores le orientarán en cada caso.',
    'fare.economy': 'Clase Económica',
    'fare.checkedBaggage': 'Equipaje facturado',
    'fare.bagIncluded': 'maleta incluida',
    'fare.bagsIncluded': 'maletas incluidas',
    'fare.totalPerPerson': 'Precio total por persona',
    'checkout.title': 'Finalizar Reserva',
    'checkout.subtitle': 'Complete los datos para confirmar su viaje',
    'checkout.back': 'Volver a la búsqueda',
    'checkout.whoTravels': '¿Quién viaja?',
    'checkout.contactData': 'Datos de Contacto',
    'checkout.contactSub': 'donde enviaremos el enlace de pago e información de la reserva',
    'checkout.email': 'Correo electrónico',
    'checkout.whatsapp': 'WhatsApp *',
    'checkout.whatsappPlaceholder': '55 (DD) 99999-9999',
    'checkout.paymentMethod': 'Método de Pago',
    'checkout.paymentMethodSub': 'Cómo prefiere pagar su viaje',
    'checkout.payment.pix': 'Pix',
    'checkout.payment.boleto': 'Boleta Bancaria',
    'checkout.payment.card': 'Tarjeta de Crédito',
    'checkout.payment.crypto': 'Criptomonedas',
    'checkout.submit': 'Continuar',
    'checkout.processing': 'Procesando...',
    'checkout.paymentDetails': 'Detalles de Pago',
    'checkout.flightFor': 'Vuelo para',
    'checkout.taxes': 'impuestos y tasas',
    'checkout.total': 'Total',
    'checkout.successTitle': '¡Reserva en Curso!',
    'checkout.successMessage': `Su reserva está en curso. Un especialista de Bit Travels se comunicará por WhatsApp ${WHATSAPP_DISPLAY_NUMBER} para finalizar la reserva y el pago.`,
    'checkout.bookingId': 'ID de Reserva',
    'checkout.talkToSpecialist': 'Hable con un Agente',
    'passenger.adult': 'Adulto',
    'passenger.child': 'Niño',
    'passenger.baby': 'Bebé',
    'passenger.fillData': 'Complete los datos según el documento',
    'passenger.nameLabel': 'Nombre *',
    'passenger.nameSub': 'Como aparece en el documento',
    'passenger.lastNameLabel': 'Apellido *',
    'passenger.lastNameSub': 'Ej: García',
    'search.select': 'Seleccionar',
    'search.backpackOption': 'Incluye un artículo personal',
    'search.backpackSub': 'Debe caber debajo del asiento delantero.',
    'search.carryonOption': 'Incluye equipaje de mano',
    'search.carryonSub': 'Debe caber en el compartimento superior del avión.',
    'search.noCheckedOption': 'No incluye equipaje facturado',
    'search.noCheckedSub': 'Puede añadir maletas por un valor adicional.',
    'fare.fallbackLabel': 'Tarifa Disponible',
    'fare.fallbackName': 'Tarifa',
    'fare.selected': 'Seleccionado',
    'search.roundTripFare': 'Tarifa para Ida y Vuelta',
    'search.errorTitle': 'Error al buscar vuelos:',
    'search.priceCombination': 'combinación de precio',
    'search.priceCombinations': 'combinaciones de precio',
    'passenger.babies': 'Bebés',
    'nav.flights': 'Vuelo',
    'ticket.print': 'Imprimir Boleto',
    'ticket.generating': 'Generando su boleto...',
    'ticket.status': 'Confirmado',
    'passenger.country': 'País de residencia',
    'passenger.selectCountry': 'Seleccione el país',
    'passenger.documentType': 'Tipo de documento',
    'passenger.selectDocument': 'Seleccione el tipo',
    'passenger.passportRequired': 'Obligatorio para pasajeros residentes fuera de Brasil',
    'passenger.document': 'Documento',
    'passenger.birthDate': 'Fecha de nacimiento',
    'passenger.day': 'Día',
    'passenger.month': 'Mes',
    'passenger.year': 'Año',
    'passenger.gender': 'Sexo',
    'passenger.female': 'Femenino',
    'passenger.male': 'Masculino',
    'passenger.month.jan': 'Enero',
    'passenger.month.feb': 'Febrero',
    'passenger.month.mar': 'Marzo',
    'passenger.month.apr': 'Abril',
    'passenger.month.may': 'Mayo',
    'passenger.month.jun': 'Junio',
    'passenger.month.jul': 'Julio',
    'passenger.month.aug': 'Agosto',
    'passenger.month.sep': 'Septiembre',
    'passenger.month.oct': 'Octubre',
    'passenger.month.nov': 'Noviembre',
    'passenger.month.dec': 'Diciembre',
    'country.brasil': 'Brasil',
    'country.argentina': 'Argentina',
    'country.chile': 'Chile',
    'country.colombia': 'Colombia',
    'country.estados unidos': 'Estados Unidos',
    'country.portugal': 'Portugal',
    'country.espanha': 'España',
    'country.franca': 'Francia',
    'country.italia': 'Italia',
    'country.alemanha': 'Alemania',
    'country.outro': 'Otro',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('pt')

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language
    console.log('[LanguageContext] Idioma salvo no localStorage:', saved);

    if (saved && (saved === 'en' || saved === 'pt' || saved === 'es')) {
      setLanguageState(saved)
    } else {
      console.log('[LanguageContext] Iniciando detecção automática por IP...');
      detectUserLanguage().then((lang) => {
        console.log(`[LanguageContext] Detectado idioma: ${lang}`);
        setLanguage(lang);
      });
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
